AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  KeyPairName: 
    Type: String
    Description: EC2 Key Name
  VpcId:
    Type: String
    Description: VPC Id
  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref 'LatestAmiId'
      InstanceType: t3.small
      SecurityGroupIds:
      - !GetAtt SSHSecurityGroup.GroupId

  myS3Bucket1:
    Type: AWS::S3::Bucket

